---
- hosts: appserver
  become: yes
  tasks:
    - name: ping all
      ping:
    - name: dispaly name od package of instalation
      debug:
        msg: "{{package_install}}"

    - name: instalation of  "{{package_install}}"
      yum: 
        name: "{{package_install}}"
        state: present
      notify:
      - restarthttpd
      when: ansible_os_family=="RedHat"

    - name: instalation of  "{{package_install}}"
      apt: 
        name: "{{package_install}}"
        state: present
      notify:
      - restarttomcat
      when:  ansible_os_family=="Debian" 

    - name: add the tomcat change jvm heap memory
      template:
        src: tomcatjvm.j2
        dest:  /etc/default/tomcat7
      notify: restarttomcat
      when:  ansible_os_family=="Debian"
    - name: add the tomcat user
      template:
        src: tomuser.j2
        dest:  /etc/tomcat7/tomcat-users.xml
      notify: restarttomcat
      when:  ansible_os_family=="Debian"

    - name: download the openmrs war file
      get_url:
        url: https://sourceforge.net/projects/openmrs/files/releases/OpenMRS_Platform_2.0.5/openmrs.war
        dest: /home/maha/hosts/openmrs.war
      when: ansible_os_family=="RedHat"


    - name: copy past war file in nodes
      copy: 
        src: /home/maha/hosts/openmrs.war
        dest: /var/lib/tomcat7/webapps/openmrs1.war
      notify: restarttomcat
      when:  ansible_os_family=="Debian"
  
  handlers: 
    - name: restarthttpd
      service:
        name: httpd
        state: restarted   
    - name: restarttomcat
      service:
        name: tomcat7
        state: restarted  
 

