---
- hosts: appserver
  become: yes
  tasks:
    - name: ping all
      ping:
    - name: dispaly name od package of instalation
      debug:
        msg: "{{package_install}}"

    - name: instalation of  "{{package_install}}"
      yum: 
        name: "{{package_install}}"
        state: present
      notify:
      - restarthttpd
      when: ansible_os_family=="RedHat"

    - name: instalation of  "{{package_install}}"
      apt: 
        name: "{{package_install}}"
        state: present
      notify: 
      - restarttomcat
      when:  ansible_os_family=="Debian" 
    - name: download the openmrs war file
      get_url:
        url: https://sourceforge.net/projects/openmrs/files/releases/OpenMRS_Platform_2.0.5/openmrs.war
        dest: /var/lib/tomcat7/webapps/openmrs.war
      notify:
      - restarttomcat
      when:  ansible_os_family=="Debian"

  handlers: 
    - name: restarthttpd
      service:
        name: httpd
        state: restarted   
    - name: restarttomcat
      service:
        name: tomcat7
        state: restarted  
 
