---
- hosts: appserver
  become: yes
  tasks:
    - name: installing tomcat 
      yum:
        name: tomcat
        state: absent
    - name: just cheeking groups varibles
      debug:
        msg: "{{log_folder}}"