---
- hosts: all
  become: yes
  tasks:
    - name: install apache on redhat
      yum:
        name: httpd
        state: present
      when: ansible_os_family=="RedHat"
      #when: not ansible_os_family=="RedHat"
      tags:
        - install
    - name: install apache on ubounto
      yum:
        name: apache2
        state: present
      when: ansible_os_family=="Debian"
      #when: not ansible_os_family=="RedHat"
    - name: print free memory
      debug:
        msg: "free memory is {{ansible_memory_mb.real.free}}"

