---
- hosts: all
  become: yes
  tasks:
    - name: install httpd on redhat
      yum:
        name: httpd
        state: present
      #when: ansible_os_family=="RedHat"
      when: not ansible_os_family=="RedHat"
    - name: install apache on uboumtu
      yum:
        name: apache
        state: present
      #when: ansible_os_family=="Debian"
      when: not ansible_os_family=="debian"
